## 1.Creat a 3x3x3 array with random values

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.94149348 0.34964311 0.08784585]
  [0.13452593 0.73438593 0.7363297 ]
  [0.72847591 0.88624982 0.84233944]]

 [[0.8242836  0.07925486 0.42914886]
  [0.1926864  0.70538682 0.15321528]
  [0.89272767 0.14829134 0.04603105]]

 [[0.14148815 0.82675922 0.91741083]
  [0.00407128 0.90701112 0.59848754]
  [0.02899066 0.42511666 0.74998054]]]


## 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal


In [3]:
x = np.diag(1 +np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 3.Create a 8x8 matrix and fill it with a checkerboard pattern


In [4]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 4.Normalize a 5x5 random matrix

In [6]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.9141087  0.24104086 0.38531147 0.96994879 0.42434177]
 [1.         0.65967277 0.63682747 0.         0.36552819]
 [0.1353901  0.24056653 0.52906224 0.4048462  0.58844697]
 [0.57502562 0.03805904 0.02646708 0.13809927 0.86020697]
 [0.85491724 0.76918786 0.70255979 0.05963211 0.02337209]]


## 5. How to find common values between two arrays?

In [7]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


## 6.How to get the dates of yesterday, today and tomorrow?

In [8]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


## 7. Consider two random array A and B, check if they are equal

In [10]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 1 1 0 0 0]
Second array:
[1 0 0 0 1 0]
Test above two arrays are equal or not!
False


## 8.Create random vector of size 10 and replace the maximum value by 0

In [28]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.74916957 0.75002958 0.31198342 0.2690409  0.6238769  0.78823227
 0.08811184 0.13015725 0.89884178 0.79061698]
Maximum value replaced by 0:
[0.74916957 0.75002958 0.31198342 0.2690409  0.6238769  0.78823227
 0.08811184 0.13015725 0.         0.79061698]


## 9. How to print all the values of an array?

In [29]:
my_array = np.arange(30)
np.set_printoptions(threshold=np.inf)
print(my_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


## 10.Subtract the mean of each row of a matrix

In [30]:
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[0.51725775 0.12016436 0.77149297 0.71249015 0.01329508 0.85591571
  0.22592674 0.8690755  0.72183436 0.9190513 ]
 [0.73780145 0.07876738 0.53210846 0.08708302 0.57783845 0.66266656
  0.76158599 0.29132349 0.37654751 0.12974486]
 [0.33443681 0.80060757 0.8033212  0.47951612 0.5930747  0.49275963
  0.38468477 0.04125603 0.58114576 0.30286995]
 [0.73040589 0.23956126 0.57538236 0.89985825 0.96474385 0.29948095
  0.73732382 0.08938205 0.84596404 0.54967156]
 [0.07769902 0.81660556 0.04037942 0.78902445 0.87667107 0.57478816
  0.15702564 0.14939809 0.03048343 0.4558974 ]]

Subtract the mean of each row of the said matrix:

[[-0.05539264 -0.45248604  0.19884258  0.13983976 -0.55935531  0.28326532
  -0.34672366  0.29642511  0.14918397  0.34640091]
 [ 0.31425474 -0.34477934  0.10856174 -0.3364637   0.15429173  0.23911984
   0.33803927 -0.13222323 -0.0469992  -0.29380186]
 [-0.14693045  0.31924032  0.32195395 -0.00185114  0.11170745  0.01139237
  -0.09668249 -0.44011122  0.0

## Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [31]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)


[5. 1. 1. 4. 1. 1. 2. 4. 7. 4.]


## 12.How to get the diagonal of a dot product?

In [38]:
A=[1,5,7,9,2]
B=[4,6,2,4,7]
def diag(A,B):
    diags = []
    for x in range(len(A)):
        diags.append(A[x][x] * B[x][x])
    return diags
diag

<function __main__.diag(A, B)>

## 13.How to find the most frequent value in an array?

In [39]:
def mostFrequent(arr, n): 
    arr.sort() 
    max_count = 1; res = arr[0]; curr_count = 1
      
    for i in range(1, n):  
        if (arr[i] == arr[i - 1]): 
            curr_count += 1
              
        else : 
            if (curr_count > max_count):  
                max_count = curr_count 
                res = arr[i - 1] 
              
            curr_count = 1
   
    if (curr_count > max_count): 
      
        max_count = curr_count 
        res = arr[n - 1] 
      
    return res 
  

arr = [1, 5, 2, 1, 3, 2, 1]  
n = len(arr) 
print(mostFrequent(arr, n))

1


## 14.How to get the n largest values of an array

In [40]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


## 15.How to create a record array from a regular array

In [41]:
import numpy as np
arra1 = np.array([("Yasemin Rayner", 88.5, 90),
                 ("Ayaana Mcnamara", 87, 99),
             ("Jody Preece", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Yasemin Rayner' '88.5' '90']
 ['Ayaana Mcnamara' '87' '99']
 ['Jody Preece' '85.5' '91']]

Record array;
[(b'Yasemin Rayner', 88.5, 90) (b'Ayaana Mcnamara', 87. , 99)
 (b'Jody Preece', 85.5, 91)]
